### PR TITLE
Add redis as alternative storage for server

### PR DESCRIPTION
**Pull request by eirikeikaas**
Storing the database as a file on disk doesn't work well with ephemeral systems such as Heroku. This splits the database into different stores and implements redis as an alternative to disk.

### CODE REVIEW

**Comment by inlife** [comment]
Hey @eirikeikaas 

Great pull request. A lot of people were asking for the Redis support, hehe! 🎉 

One question from me to you though: how do you think, would it be a good idea to split off a Redis into a separate package? That is something I want to do with the change you proposed. 2 reasons for that:
* More different database backend packages could be added later on by other people (mongodb, MySQL, postgre, dynamodb, etc.)
* People would opt-in only for what do they need to actually use

Cheers!

**Comment by eirikeikaas** [comment]
@inlife nice!

Creating separate packages for this makes a lot of sense so I'll update this PR accordingly 👌 .

**Comment by eirikeikaas** [comment]
@inlife This should be good now if you want to take a look.

* Packages are picked up from the database.js helper similar to the provider implementation in nexrender-core
* The former database/disk implementation is moved to a helpers/disk.js and works as before and as the default
* Database provider is chosen using NEXRENDER_DATABASE_PROVIDER

**Comment by inlife** [comment]
Amazing job @eirikeikaas ! 🎉 
That is exactly what I was thinking about!

**Comment by eirikeikaas** [comment]
This should be all good to merge. All endpoints in the server API works as expected with both disk and redis implementations 👍 .

**Comment by inlife** [comment]
Released as `v1.28.0`
Great job @eirikeikaas 🎉 😄

**Comment by eirikeikaas** [comment]
Perfect, and thanks! Happy to contribute to this amazing project of yours 🔥

**Pull request merged**
