### PR TITLE
Feature: tag selector, worker to pickup job wiith specific tags

### PR DESCRIPTION
**Pull request by mohali-id**
Hi @inlife 

I'm adding a tag selector option on the worker, so the worker can pickup a job with specific tags.

For example.
If i create these job on the server

Explanation:  _Worker 1_ can only pick up _Job 1_ because only _Job 1_ meet the criteria (by tags).  However, _Worker 2_ can pick up _Job 1_ or _Job 2_ or any other Jobs on the server.

What do you think?

### CODE REVIEW

**Comment by inlife** [comment]
@mohali-id Looks good! 👍 

I would also add some trimming to tags after they've been provided and probably some regex checks to comply with the validity of input symbols. `[a-z0-9]` should be ok. But please, consider those to be more of a recommendation from my side rather than a requirement. 

I see there is an addition of Priority as well, but so far does not seem there is any functionality added for it. Is it planned for the next commit?

**Comment by mohali-id** [comment]
Nice recommendation, I agree to add some regex checks to trim the provided tags. Should i add them to my next commit or on your side?

For **Priority,** I just adding a description. the functionality was in [there](https://github.com/inlife/nexrender/tree/master/packages/nexrender-server) and it works very well.

**Comment by inlife** [comment]
I would really appreciate it if you could add it to the next commit. If that is ok with you!

Ah, indeed. I already forgot about that priority feature 😅

**Comment by mohali-id** [comment]
That's ok for me. My new commit just arrived with those changes base on your recommendation.

Thank you!

**Pull request merged**
