### PR TITLE
Dynamically-Injected JSX Parameters

### PR DESCRIPTION
**Pull request by dukuo**
🚀 Scripting on steroids 🚀
 
With this pull request [Nexrender](https://github.com/inlife/nexrender) will have support for custom parameters injected right into a JSX script! 💥 💥 💥 

It's a flexible approach to handle variables, objects and functions by using simple JSX patterns with cross environment fault tolerance, allowing the possibility to run the script straight in After Effects provided you set local defaults for Nexrender variables. 

For more information check out **README.md** or read the code documentation.

**_NOTES:_**
This is the most complete code I could  come up in a day, with all of the edge cases I could think of. There are some tested JSX and JSON files at the **test** folder, please check them out and let me know if there was something I didn't think of so we can patch it up swiftly. Also, I tested from `nexrender-cli` but i'm assuming that using `render` programatically will work correcetly as well.

Cheers!

### CODE REVIEW

**Comment by dukuo** [comment]
TODO: Handle edge case where the initialiation variable is set on the JSX script, but is commented.

**Comment by inlife** [comment]
I gotta say, It's very well done, amazingly covered both docs and code with extensive descriptions and examples. I like it a lot!

One major thing I have to ask first tho, why did you decide to add yarn.lock, and is it needed?

**Comment by dukuo** [comment]
Thanks for the review! I appreciate the comments, I was hooked while coming up with the solution, specially since it was a rainy day with some chill music ☁️  

As for the `yarn.lock` It's because i'm currently using Yarn, and while searching on google found this [GitHub issue](https://github.com/yarnpkg/yarn/issues/1583): 

> You should add yarn.lock to your git, don't ignore it.

>See https://yarnpkg.com/en/docs/migrating-from-npm

>When you run either yarn or yarn add <package>, Yarn will generate a yarn.lock file within the root directory of your package. You don’t need to read or understand this file - just check it into source control. When other people start using Yarn instead of npm, the yarn.lock file will ensure that they get precisely the same dependencies as you have.

**Comment by inlife** [comment]
Ok, I see the reasoning, however, could you please remove it?
Package has a very minimal dependency tree, and something like that, or even npm-lock is not really needed, hence the reason it's not used there as well.

Regarding TODOs you mentioned above, do you wish to work on them for some time, in this PR?
I can merge it later when you feel that everything is 100% done.

**Comment by inlife** [comment]
Oh and, could you actually send me a final generated script file with some custom params passed from the job, I want to see how it looks as a result.

**Comment by dukuo** [comment]
Yeah I could do that. I'm going to sleep a while and then come back with the changes.  

Also will update the code with a sample of the generated code to show the result.

**Comment by inlife** [comment]
Great, thanks for the hard work!

Cheers!

**Comment by dukuo** [comment]
Alright, edge case of usage in comment lines / blocks is implemented, and a test case JSX script was added. 

The documentation was updated to include a sample compiled script, as well as in the script.js code documentation. 

As for :
>Enable multiple Default Parameter options for different parameter types (string, boolean, number, function, etc.) 

Since the goal is to have minimal dependencies i'm choosing not to go further with this case for now, since the current implementation of filling all found parameters with `null` in case of no `JSX` nor `JSON` parameter initialization seems to work fine for now. 

And finally, `yarn.lock` was removed to avoid Yarn dependency.

**Comment by dukuo** [comment]
Actually, i'll implement one more thing before the merge if that's okay with you.

**Comment by inlife** [comment]
Feel free to do any additional changes as you see fit, and then just notify me, when its going to be ready to merge.

**Comment by dukuo** [comment]
Okay, I think i'm done for the moment. Added a `globalDefaultValue` to enable a global fallback in case of unknown or undefined values for any given `keyword` object child `key`. 

This should cover most of the common use cases. Thanks a lot for the feedback so far.

**Comment by danielgwilson** [comment]
@dukuo this is **awesome**. Highly needed, thanks for implementing.

—

Regarding the `parameters: { key: string, value: any }` approach—why not just make the parameters field accept an object?

For example:

Now:
```typescript
{
    type: "script",
    src: path.join(resourceDir, "/ae-scripts/", "section-title.js"),
    keyword: "NX",
    parameters: [
        key: "myKey",
        value: "myValue"
    ]
  }
```

Proposed:
```typescript
{
    type: "script",
    src: path.join(resourceDir, "/ae-scripts/", "section-title.js"),
    parameters: {
        NX: {
            key: value
        }
    }
  }
```

Thoughts?

**Comment by dukuo** [comment]
> @dukuo this is **awesome**. Highly needed, thanks for implementing.
> 
> —
> 
> Regarding the `parameters: { key: string, value: any }` approach—why not just make the parameters field accept an object?
> 
> For example:
> 
> Now:
> 
> ```ts
> {
>     type: "script",
>     src: path.join(resourceDir, "/ae-scripts/", "section-title.js"),
>     keyword: "NX",
>     parameters: [
>         key: "myKey",
>         value: "myValue"
>     ]
>   }
> ```
> 
> Proposed:
> 
> ```ts
> {
>     type: "script",
>     src: path.join(resourceDir, "/ae-scripts/", "section-title.js"),
>     parameters: {
>         NX: {
>             key: value
>         }
>     }
>   }
> ```
> 
> Thoughts?

Thanks! I'm close to send a new PR with a complete rework of the code, which maintains the same schema you are discussing at the moment. The current approach uses an array of `key: string, value: string|array|object|null` objects to allow multiple custom parameters in your script. Am I missing something? The current code implements a key/value approach in a way that literally uses the object's `key` and `value` children, but honestly it was my first approach to it.

**Pull request merged**
