### PR TITLE
Feat: WSL support

### PR DESCRIPTION
**Pull request by Klastic**
Adds support for WSL (Windows Subsystem for Linux).

### Overview

Currently `nexrender` does not support users who are using `WSL`. This PR adds support for these users with little change to base code.

>Init Issue [Is it possible to run Nexrender from WSL2?](https://github.com/inlife/nexrender/issues/422)

### Testing
Tested on `Windows` and `WSL`.

Will need to be tested on `macOS`, though I do no believe it should have affected it.

### Feedback

Feedback on ways to `improve` or `issues` with the design are welcome.

### CODE REVIEW

**Comment by inlife** [comment]
Hey @Klastic 

Changes for WSL support look great!
I can't merge this right now, however, since it also contains a lot of formatting changes that do not actually change anything. Most likely they were generated by your editor. Could you go through every change and revert it to the way it was, unless that is something that you actually did for WSL?

So that PR would reflect only actual changes, and it would "respect" the existing codebase.

Thank you!

**Comment by Klastic** [comment]
They were not intended, habit from working on projects with prettier and auto formatting before save.

Do you have, or would you be willing to create a prettier config with your standard for the codebase? It would save me a great deal of time vs trying to find and revert the changes. It could also create a standard for others who contribute to the project and use auto formatting. 

If not, that is understandable and I will try my best once I have a few hours to correct the formatting changes imposed by my config.

**Comment by inlife** [comment]
Hey, created a small config for prettifier, you can add it directly into this PR as well:
```js
module.exports = {
    trailingComma: 'es5',
    tabWidth: 4,
    useTabs: false,
    semi: false,
    singleQuote: true,
    proseWrap: 'never',
    arrowParens: 'avoid',
};
```

My only worry is that it won't fix all of the issues since I could not even find some options on their website to do such formatting things. Let's try, however. After you push with the changes, and re-save and also push files that you've worked with, we will look at it again. Does that sound good?

**Comment by Klastic** [comment]
Hey @inlife, I added in the prettierrc.json file and formatted the files that I touched. It does not seem it corrected some of the wrapping issues and it looks to have updated a bit of the code which was not following the standard you specified.

If this is still not ideal I can look a creating a new branch/PR and copying over the WSL code and skip my normal formatting step.

**Comment by inlife** [comment]
Well, actually, a new PR with "clean" changes with the things that only you've added for WSL would be just a perfect solution, I think.

**Comment by Klastic** [comment]
Understood, once I get a bit of time I will open a new PR.

**Comment by inlife** [comment]
Thank you, I really appreciate you dealing with all that trouble.

**Pull request closed without merging**
