### PR TITLE
Update commandLineRenderer.jsx script from After Effects 2022

### PR DESCRIPTION
**Pull request by chrisapplegate**
This update does the following:

- The commandLineRenderer.jsx is updated to use the latest version from After Effects 2022, with the `-r` patch nexrender needs added on top.
- The code for setting multi-frame renders has been updated to use the new `-mfr` flag (see the [updated docs](https://helpx.adobe.com/after-effects/using/automated-rendering-network-rendering.html))
- An additional optional parameter, `multiFramesCPU` has been added in to set the second value in `-mfr`, the CPU percentage multi-frame rendering should take. It defaults to 90 which corresponds to the 10% reserved for other applications  default in After Effects' Preference pane.

### CODE REVIEW

**Comment by inlife** [comment]
The best strategy atm would be to have two versions of the commandLineRenderer, one for pre2022 and another for 2022+. It probably would be a good idea to have some sort of "multi-version support" for future-proofing. In case adobe decides to add more breaking changes in future releases.

Best way to choose which version to use would probably be a file path recognition for the binary path, with an option of manual override via argument. 

Which pros and cons do you see right away @chrisapplegate ?

**Comment by chrisapplegate** [comment]
> Best way to choose which version to use would probably be a file path recognition for the binary path, with an option of manual override via argument.

I think that's already there - in [patch.js](https://github.com/inlife/nexrender/blob/76414019c17193055c0e46ca19fba1944c884ec0/packages/nexrender-core/src/helpers/patch.js) it just uses the `binary` specified in `settings` - which is either autodetected or set on the command line with `--binary`

So I think all you need to do is detect the year inside the value of `settings.binary`, and if it exists and it is >= 2022, patch in the 2022 `commandLineRenderer.jsx`, else fall back to the original `commandLineRenderer.jsx`...

**Comment by chrisapplegate** [comment]
@inlife I have had a stab at using the above to detect the year and allocate a commandLineRenderer.jsx accordingly. Let me know what you thinbk

**Comment by inlife** [comment]
That works! Great job, thank you for the great improvement! :)

**Pull request merged**
