### PR TITLE
Feature/add extension to destname

### PR DESCRIPTION
**Pull request by stoikheia**
hello,
i have a suggestion.
this modification adds extension to downloaded (or copied) file for layer that named without extension.

commit message:
```
Added extension to destName of download.

AE required extension to recognize file type.
AE returns error if downloaded file is no extension.
it occurs when layer name without extension.
```

(AE version 16.1.1)
i encountered this error when i want to replace audio file of various type into a layer named without extension.

it will name two extensions if layer name has extension, but i think it will not bad affect.

### CODE REVIEW

**Comment by stoikheia** [comment]
sorry, above commit is wrong code.
i'll fix that as below.

```
function createDestName(asset, protocol) {
    switch (protocol) {
        case 'data':
            /* if asset doesnt have a file name, make up a random one */
            return asset.layerName ?
                asset.layerName :
                Math.random().toString(36).substring(2);
        case 'file':
            return path.basename(asset.src);
        default:
            if (path.parse(asset.layerName).ext) {
                return asset.layerName;
            }
            return path.basename(asset.src);
    }
}
```
However, that rule is bit complexity.
for simplification,  i think it have to be added a parameter 'destName' into asset item.

and it has another problem in current code and my code.
result will be corrupted if it is duplicated each layers `path.basename(asset.src)` and `asset.layerName`.
(if actual files are different that duplicated.)
i think it could be avoided by adding parameter into asset such as 'destName' explicitly.

also, adding the parameter 'destName' into asset will not destroy backward compatibility.

**Comment by inlife** [comment]
The only problem I think there is with adding a destName explicitly is additional complexity and verbosity from user point of view. When I imagine I would need to type each that name manually, even the probability of me making a mistake is going up )

I think we need to try possibly to figure out a bit nicer, more robust and less verbose method.
What do you think?

**Comment by inlife** [comment]
i added a commit that might partially fix the issue

**Comment by inlife** [comment]
Since destName is a temporary file which in theory we don't really care about we can disregard the ability to set it manually. The current solution simply uses either basename of the downloaded asset, or  (if it is already taken) creates a random name, however, keeps the original file extension.

Having that, I don't see the need in the PR any longer.

**Pull request closed without merging**
