### PR TITLE
Add download lifecycle actions and @nexrender/action-cache

### PR DESCRIPTION
**Pull request by dylangarcia**
# Action: Cache

Cache your template source to a specified location and reuse it on subsequent runs

## Installation

```
npm i -g @nexrender/action-cache
```

## Usage

When creating your render job provide this module in **both** of the `predownload` and `postdownload` actions:

```js
// job.json
{
    "actions": {
        "predownload": [
            {
                "module": "@nexrender/action-cache",
                "cacheDirectory": "~/cache"
            }
        ],
        "postdownload": [
            {
                "module": "@nexrender/action-cache",
                "cacheDirectory": "~/cache"
            }
        ],
    }
}
```

### CODE REVIEW

**Comment by inlife** [comment]
This feature looks amazing! @dylangarcia 

I have only one question though, how do you think, wouldn't it be even better to extend support for caching from template file only, to any asset, including template files? That would allow caching everything if needed. 

And for specific cases where some of the assets would not need to be cached, some sort of `cache: false` flag could be used on those specific entries.

What do you think?

**Comment by dylangarcia** [comment]
So, the original impetus for this action was that my workflow is downloading a .zip file from gs:// which contains all of the assets, which is then unzipped using the other package I created. I'm not really sure about extending support for _all_ assets, because how do we know they exist?

**Comment by inlife** [comment]
For those assets, I was more referring to a more general approach within nexrender (assets within job.assets array).
If you think that is something not worth looking into, it's fine. I just thought that would be a good addition to your feature. 👍

**Comment by dylangarcia** [comment]
Ah, I don't quite think I noticed `jobs.assets` being a thing 😅 I think for now I'd probably prefer to skip the other assets, but it's probably a good/easy issue for somebody to take up if they need that support?

**Comment by inlife** [comment]
Sounds fair! In that case, I think it's ok to merge, or are you thinking about adding more changes?

Btw: I hope you don't mind me asking, are you working at webflow?

**Comment by dylangarcia** [comment]
This is good for what I personally need 👍 

And yes, I am 😄

**Comment by inlife** [comment]
> And yes, I am 😄

That is very cool! Do you mind joining our discord, would be cool to chat with you a bit! 😄

**Pull request merged**
