### PR TITLE
Complete rework of Dynamic Parameter Injection. 

### PR DESCRIPTION
**Pull request by dukuo**
:rocket: Now with bug-free (*) support for **functions**!  :rocket:

The code was completely rewritten in a cleaner, streamlined way, as well as the introduction of the `ParameterConfigurator` `prototype`, which is a flat `key`/`value`store that works as an injection engine of the implementation. 

Main changes:

* Now instead of `NX.foo` you must use `NX.get("foo")`. 
* **NEW!**: To call stored functions use `NX.call("mymethod")` and `NX.call("mymethod", ["stringArg", 42])` for methods using arguments. You can also interchange `NX.get()` with `NX.call()` if you know your stored value is a function, because under the hood `NX.get()` checks for a function and if so passes it with arguments to `NX.call()`
* Documentation update with more examples and usage changes. 

I'm very excited with this code, and i'm planning on creating a standalone library called [Potat](https://github.com/dukuo/potat) to further explore this way of using JSON to generate Javascript code, and to incentivize bug fixes which can be mirrored into `nexrender` as well. 

<sup><sub>__(*) Chance of bugs may still be present. Like in, you know, every piece of software that's ever been created.__</sup></sub>

### CODE REVIEW

**Comment by inlife** [comment]
Another amazing pull request!

I can see that custom function stuff goes quite deeply now since custom functions become a kind of a base for more, and allow additional, even more, complex stuff to be built upon. I'm wondering now, should we maybe extract all of this from script asset type, and create a new type for it. Or even a separate json `job` entry, like `job.data` or something like that.

It seems to me it can become some sort of a data layer that could be accessible in all scripts defined in the job, and even further possible in all expressions as well. Not yet sure if it is technically possible tho.

What do you think @dukuo

**Comment by dukuo** [comment]
That's an interesting idea! A shared context between scripts in a `data` section of a `job`. I like it! 

I guess that expressions could have some sort of communication as well, i'm researching some possible approaches to it; let's sit this PR for a bit until we get the full scope of what we can achieve with this new approach.

**Comment by inlife** [comment]
I figured we can go even more advanced and introduce a paired environment. Right now, all of the scripting stuff is happening inside of the After Effects engine. To add any external dynamic values/data to the scripts you would need to prefetch them before starting and inject them.

However, we can modify your ParameterConfigurator to actually work as a bidirectional data-binding layer on top of the TCP connection that can be created using `Socket` object in the scripting env, and a simple TCP server in nexrender-core part. That would mean that any .call/.get operation (on a function) would actually trigger a remote function that would execute on nexrender (nodejs) side, with access to anything you would want to have access to, like databases, HTTP API requests, you name it, and then return the result to the scripting env. Basically your project `Potat` would be able to use any es6 language constructs since it would be executed on nodejs side of things.

Calling .set method from the scripting side would directly set values for related expressions to update their current data. (Since expressions can't have access to anything above the expression itself, we can do it only one-directional way, and that would limit expressions from being able to use .set)

And in turn, going further, we can even introduce async-based `.set`, and some sort of `.call` calls (call functions that were attached via `.bind` or something like that) from the nodejs side, which would trigger a network request update the overall state to the scripting & expressions, pretty much giving you the ability to control everything externally.

**Comment by inlife** [comment]
Possibly my mind went too far, and all the things that I wrote could actually be made later since they kinda sound like a major change to the whole system and would probably be a nice feature next major release (`v2.0.0`)

So as a simpler alternative we can merge this PR rn, if you feel like you finished with it, and eventually, I'll start working on a major update.

**Comment by dukuo** [comment]
Alright sounds like a very interesting challenge. Let me give it a moment before we merge this PR, I want to come up with a basic attempt at it.

**Comment by danielgwilson** [comment]
On the other hand—these changes are breaking and (as a best practice) should maybe have merited a major version bump.

Fairly straightforward fix, though.

**Comment by danielgwilson** [comment]
Also—sorry for the spam posts, just commenting as I'm reading more / thinking about this—what's up with the move to `NX.get("")` and `NX.call("")`?

I find this a bit uglier than previously... is there not some clean way to get a standard JS object into the script without all these weird wrappers?

**Pull request merged**
