### PR TITLE
 Forward all parameters to aerender #452

### PR DESCRIPTION
**Pull request by brassel**
As discussed in https://github.com/inlife/nexrender/issues/446.

### CODE REVIEW

**Comment by inlife** [comment]
Looks good so far!
How do you think @brassel is that something worker can benefit from as well?

**Comment by brassel** [comment]
@inlife I have not used the worker so far. We only use the cli. Is there another file you would like me to edit in the same spirit? I could gladly do that but would ask you to do the testing for that. Ok with you?

**Comment by inlife** [comment]
Yep, since both cli and worker use the core, you already did most of the job. Only thing left is to pass parameters same way you did in the cli. Take a look at this: https://github.com/inlife/nexrender/blob/master/packages/nexrender-worker/src/bin.js

**Comment by brassel** [comment]
I have added the requested functionality and will open a new pull request.

**Pull request closed without merging**
