### PR TITLE
Fix FTP connection on Windows

### PR DESCRIPTION
**Pull request by benjioh5**
patch of #555 isue

### CODE REVIEW

**Comment by benjioh5** [comment]
WIP, doo not merge

**Comment by benjioh5** [comment]
Commit https://github.com/inlife/nexrender/commit/712697babc1a42c506a99e1b6ffbf2bb3a4be8cb replaces this pull request.

**Comment by avsecuri** [comment]
Has this issue been resolved yet, experts? I am using the latest version (1.26.3) but the error still persists.
image

**Comment by inlife** [comment]
@avsecuri could you provide your job configuration description?

**Comment by avsecuri** [comment]
@inlife what should I provide? I checked the ftp account, it's valid.
```
"actions": {
    "postrender": [
        {
            "module": "@nexrender/action-upload",
            "input": "result.mp4",
            "provider": "ftp",
            "params": {
                "host": "***",
                "port": 21,
                "user": "***",
                "password": "***",
                "output": "/home/uploads/result.mp4"
            }
        }
    ]
}
```

**Comment by inlife** [comment]
nexrnder uses this library (https://github.com/mscdex/node-ftp) internally for the ftp connection. Could you install that library locally, and try manually triggering upload with a code similar to this:

```js
const FTP = require('ftp');

const filename = 'result.mp4'
const con = new FTP();
const params = {
    "host": "***",
    "port": 21,
    "user": "***",
    "password": "***",
    "output": "/home/uploads/result.mp4"
}

c.on('ready', function() {
    c.put(filename, params.output, function(err) {
        if (err) throw err
        c.end()
    })
})

delete params.output
c.connect(params)
```

**Comment by inlife** [comment]
Ok, thanks. So the problem is within nexrender for sure.

That is indeed weird, however, since I do not see any difference with the approach in the nexrender codebase. Can you maybe find some differences with the code highlighted here: https://github.com/inlife/nexrender/blob/master/packages/nexrender-provider-ftp/src/index.js#L57-L83 ?

**Comment by avsecuri** [comment]
@inlife I'm not good at nodejs, I have additional information, I have to commented line `delete params.output` for it to work
```js
const FTP = require('ftp');

const filename = 'text.txt';
const c = new FTP();
const params = {
    "host": "",
    "port": 21,
    "user": "",
    "password": "",
    "output": ""
}

c.on('ready', function() {
    c.put(filename, params.output, function(err) {
        if (err) throw err
        c.end()
    })
})
//delete params.output
c.connect(params)
```

**Pull request closed without merging**
