### PR TITLE
Allow for reusing existing instance of AE

### PR DESCRIPTION
**Pull request by franeko**

### CODE REVIEW

**Comment by franeko** [comment]
Not really sure how to do that, could you point me to where the changes
should be made?

Vladyslav Hrytsenko <notifications@github.com> schrieb am Fr. 22. Feb. 2019
um 12:00:

**Comment by inlife** [comment]
sure, take a look at `--multi-frames` option for both:
* cli - https://github.com/inlife/nexrender/blob/master/packages/nexrender-cli/src/bin.js
* worker - https://github.com/inlife/nexrender/blob/master/packages/nexrender-worker/src/bin.js

**Comment by franeko** [comment]
Flags for binaries added

**Comment by inlife** [comment]
amazing

**Pull request merged**
