### PR TITLE
Update download.js

### PR DESCRIPTION
**Pull request by devBram97**
Added encodeURI for http and https asset sources

### CODE REVIEW

**Comment by oreporan** [comment]
This actually creates a bug with presigned_urls

similar to this:

https://stackoverflow.com/questions/30931146/aws-s3-signed-url-encode-resulting-signaturedoesnotmatch

**Comment by inlife** [comment]
How do we solve this?

**Comment by thenovelnomad** [comment]
@inlife why is nexrender taking responsibility for encoding the URI? seems like it should be the users responsibility to pass a correctly encoded URI.

**Comment by inlife** [comment]
@thenovelnomad pushed a release that removes that line (v`1.46.3`)

**Comment by thenovelnomad** [comment]
verified. thanks, @inlife!

**Pull request merged**
