### PR TITLE
Added log to the list of options

### PR DESCRIPTION
**Pull request by max-kovpak**

### CODE REVIEW

**Comment by max-kovpak** [comment]
Don't merge, pls. I'll test before.

**Comment by max-kovpak** [comment]
Done

**Comment by inlife** [comment]
hello, thank you for the pull request, successfully merged 👍 
Also, wanted to let you know, I'm planning to push updates to npm in a day or few, not right now.

**Comment by max-kovpak** [comment]
this is ok, I need this feature just locally for testing.

**Pull request merged**
