### PR TITLE
Fix error message object to string on worker

### PR DESCRIPTION
**Pull request by mohali-id**
### Fix some error message object to string on worker so we can send to our server correctly.

an error message object cannot to convert to string by using stringify. it will return an empty object ``{}``

Before:
image

After this fix:
image

### CODE REVIEW

**Comment by inlife** [comment]
Hey @mohali-id 

I support the change. However, one minor request from my side. Could we drop the ?. operator and do all needed checks here in the if statement: https://github.com/inlife/nexrender/pull/795/files#diff-bd99ff2afe0a48bc1c173aa14c7424a56bfa0d26f7893afd7f790d0ec8275b8fR97

That is done to keep the compatibility with node12 that the binaries are being built on.

Thanks!

**Comment by inlife** [comment]
Fantastic, thank you so much! 🎉

**Comment by ivansenic** [comment]
@mohali-id @inlife This PR seems to be causing that the `error` field now has value of `"[object Object]"`. So seems that in some cases this is not really working out and should be adapted.

**Comment by inlife** [comment]
Got it, I will work on a fix for this

**Comment by inlife** [comment]
@ivansenic published v1.42.2, please try it out

**Pull request merged**
