### PR TITLE
Draft: Remove dependency on match-all package, unit-tests for core script tasks

### PR DESCRIPTION
**Pull request by smukkejohan**
I wanted to create a few unittest to make sure that the changed functions work as expected in isolation. 

The way the code is structure now its quite cumbersome to make specific unittests. In projects I maintain usually I would solve this by breaking the code up into smaller modules in a sub directory that allows testing those specific methods. 

Do you have some thoughts on how to structure unittests for the project @inlife? Would it be appreciated if I take a stab at a way to add more unittests to the testsuite?

### CODE REVIEW

**Comment by inlife** [comment]
The lack of unit tests is a big issue for core and other modules indeed. 

Some of the files that were initially tiny, have grown into monsters (script, render, etc). I strongly support splitting them up into a bunch of more logical, maintainable, and testable pieces!

No strong opinion on tests, any working approach will be great!

**Comment by inlife** [comment]
And it's not going to be *just* appreciated, it would be **amazing** if you could do that! 🎉🎉🎉

**Comment by smukkejohan** [comment]
Using the original goal of this pull request as a use case I split up the structure of tasks/script into smaller components to allow for testing and added unit tests to cover the changes here. The idea for the structure is simply having *.spec.js files with unittests next to the actual components and lerna calling test on all sub projects.

@inlife do you want to take a look, I'd love to hear your feedback? 

I think when we have a structure we can work with we can merge this and then adding unit tests for more components belongs in a seperate PR that does not also change that code at the same time - otherwise merging will be way to complicated.

As for the original goal of this PR I believe the unit tests covers that it now behaves the same as before but without being dependent on an external package for regex. I also discovered some issues with the code for stripping comments that is resolved with using the strip-comments package. So +1 dep and -1, but removing one that is very small and doesn't add value and adding one that is thoroughly tested and fixes issues in the code.

I'm a little bit confused with the intention of having both .get and .call from what I can see .get will call .call. Maybe .call should not be public - also .call will not be picked up as a missing parameter, should it be?

**Comment by inlife** [comment]
I've been looking over the commits as you pushed them, it seems like a great upgrade!

I love the approach.

Also, looked over the new dep `strip-comments`, and I like the package you've chosen, 0 deps, fast. Awesome!

Regarding get vs call, can't say for sure. Maybe @dukuo will have any insights, it was his implementation a while back. The general idea, as I remember, was for .get to be a simple getter and .call to be a function trigger that accepts params and calls a registered function.

**Comment by inlife** [comment]
Are we ready to merge this @smukkejohan, or you planning making some additional changes?

**Comment by smukkejohan** [comment]
Just cleaned it up a bit, should be ready now - and we can work on additonal unit testing in seperate PR's. 

I beleive my unit tests cover that the script task produces the correct output in isolation however just be aware that I did not run any e2e tests with AE of this PR.

**Comment by inlife** [comment]
Got it! Awesome work. Thank you so much! 🎉

I'll do some additional e2e testing this weekend and push it out to release if everything goes smoothly.

**Comment by inlife** [comment]
Good news, it seems like everything is working well!

Generated a couple of heavy-scripted videos, with no problems whatsoever.

**Pull request merged**
