### PR TITLE
Added require for action-cache plugin

### PR DESCRIPTION
**Pull request by backbeatmedia**
Hello -

Please may I suggest that the plugin action-cache be added to the list of plugins required by the main code? Many thanks for your excellent project which I am learning how to use.

### CODE REVIEW

**Comment by inlife** [comment]
Hey @backbeatmedia 
Actually the change for server queues is also very awesome!

**Comment by backbeatmedia** [comment]
Hello - I'm sorry, I was going to test that before submitting it.

**Comment by backbeatmedia** [comment]
I accidentally added it to the previous pull request - I'm a bit new to Github. I need to convert the server code to run in AWS Lambda, then I can test the worker with the empty queue functionality. Can I let you know how it goes?

**Comment by backbeatmedia** [comment]
I'm going to close this pull request for now as I can see that all my fiddling is adding entries. I'll get this working then re-open. Thanks again for an excellent project.

**Comment by inlife** [comment]
Sure thing, no problem at all!

**Pull request closed without merging**
